### PR TITLE
[WIP] First attempt at smarter reconcile

### PR DESCRIPTION
**Pull request by judofyr**
TODO:

* [ ] Implement `reconcileChanges`
* [ ] `setStaticChildren` should always return an array

E.g:

```imba
<ul>
  for foo in bar
    <li> foo
```

This currently compiles to `setStaticContent(array of <li>)`, but we need it to be `setStaticContent([array of <li>]`) so that it's consistent.

### CODE REVIEW

**Comment by judofyr** [comment]
The last issue means that it will currently only work correctly if you do this:

```imba
<ul>
  <li>
  for foo in bar
    <li> foo
```

**Comment by somebee** [comment]
I can fix the inconsistency in the compiler - it drops the array of there is only one expression/child in tag. Makes no sense. Will look at the changes later today. Nice work!

**Comment by judofyr** [comment]
What do you think about this approach?

```imba
def Imba.markStatic array, id
    array:imbaStatic = id
    return array

# Generate tags like this:

t$('div').setChildren(Imba.markStatic(["Hello", other_tag], 1))
```

Then we avoid a custom method for `setStaticChildren` and it's more consistent with multiple "levels" of staticness. `setChildren` would look something like this:

```imba
def setChildren nodes
  if nodes isa Array
    if nodes:imbaStatic
      # Handle it as a static array (aka. setStaticChildren)
    else
      # Handle it as a dynamic array (aka. for-loops)
```

<hr>

As for the difference between `setChildren` and `setContent` there's this approach:

```imba
def body # on tag
    self

<foo>
  <bar>
# will generate:
t$('foo').body().setChildren(…)

<self>
  <bar>
# will generate:
t$('foo').setChildren(…)
```

If you want to implement a custom wrapper/container you can just override `body`:

```imba
tag foo
  def body
    <div@body>

  def render
    <self>
      <h1> "Menu"
      body
```

**Comment by somebee** [comment]
I really like the proposed change body().setChildren. There's one issue I'm not sure how to solve though. `<foo> <bar>` must return `<foo>`. We could cache foo before calling body like `((cached = foo),foo.body.setChildren(...),cached) but we would need to do this for every single node in the tree, since we don't know whether they have a custom implementation of body or not.

**Comment by somebee** [comment]
I've now implemented your proposed way of marking static arrays by sending them through Imba.static. Much simpler and more robust than the previous approach :) Opens up for further simplification of reconciliation.

**Pull request merged**
