### PR TITLE
better error reports

### PR DESCRIPTION
**Pull request by sleewoo**
a better variant of this judofyr/imba-loader/pull/1

### CODE REVIEW

**Comment by sleewoo** [comment]
generates errors like this:
```
ERROR in ./main.imba
Module build failed: Parse error at [27:2]: Unexpected 'COMPARE'

0
1 export def compile code, o == {}
2                           ^    
```

**Comment by somebee** [comment]
Thanks :) Will try to merge it tonight if everything works/looks okay!

**Comment by somebee** [comment]
It does mess up the error output of imba compile/watch somewhat (since it also includes the affected lines). Will try to clean it up. Should also possibly move the logic into the error itself, as it is helpful for imba.analyze and the other stages as well. Other than that, thanks for the contribution :) And sorry for the delayed response, I'm in crunch mode at work these days.

**Comment by sleewoo** [comment]
sorry for mess :)
though Imba source code is clean enough i need some time to become in use with it.

**Pull request merged**
