### PR TITLE
Reconcile text nodes

### PR DESCRIPTION
**Pull request by judofyr**
This fixes the (currently) failing tests by caching the Text objects
behind the scenes.

### CODE REVIEW

**Comment by lukeed** [comment]
Instead of creating `textNode`s, we can just create `<span>` nodes and insert the `textContent`. At that point, it functions the same as the first clause (`elif Tag`) & the DOM treats it the same as anything else.

Natively, DOM does not report `textNode` items as `children` of an element. They only "exist" as part of `.childNodes`, but this gets messy.

I have not tested this PR in my browser, but I strongly suspect that the textNodes are still going to have update/tick rendering issues, since tags' contents are determined by its [children](https://github.com/somebee/imba/blob/master/src/imba/dom/tag.imba#L674) and, as mentioned, `textNode` elements won't appear within that Collection.

---

Another idea is to embed an Imba `<text>` element, whose only purpose is to wrap a string in a `span._text`
```
tag text < span
  def render str = ''
    <self> str
```

**Comment by somebee** [comment]
We are using childNodes in the underlying dom reconciler, and it should work with actual textnodes. So we should support actual textNodes. They are already supported in all kinds of regular rendering, just not inside loops / dynamic arrays.

**Comment by lukeed** [comment]
Do you mean [here](https://github.com/somebee/imba/blob/master/src/imba/dom/tag.imba#L405)? It's the only place I found `childNodes` to be used

**Comment by somebee** [comment]
No, I mean [here](https://github.com/somebee/imba/blob/master/src/imba/dom/reconciler.imba#L187) and in  insertNestedBefore, insertNestedAfter. The reconciler is not the easiest to wrap your head around, but it does use Element#nextSibling and Element#previousSibling to walk the dom, which (like) Element#childNodes include all nodes, not just elements.

**Comment by lukeed** [comment]
👍 Perfect, thanks. Still making my way thru all the source.

**Pull request closed without merging**
